const User = require("../models/user");
const Train = require("../models/trains");

const railwayStations = [
  "Howrah Junction (HWH)",
  "New Delhi (NDLS)",
  "Mumbai Central (BCT)",
  "Chennai Central (MAS)",
  "Kolkata (KOAA)",
  "Kanpur Central (CNB)",
  "Vijayawada Junction (BZA)",
  "Ahmedabad Junction (ADI)",
  "Bhopal Junction (BPL)",
  "Pune Junction (PUNE)",
  "Patna Junction (PNBE)",
  "Bangalore City (SBC)",
  "Secunderabad Junction (SC)",
  "Thiruvananthapuram Central (TVC)",
  "Lucknow NR (LKO)",
  "Guwahati (GHY)",
  "Jaipur Junction (JP)",
  "Gwalior (GWL)",
  "Amritsar Junction (ASR)",
  "Madurai Junction (MDU)",
  "Varanasi Junction (BSB)",
  "Nagpur Junction (NGP)",
  "Bhubaneswar (BBS)",
  "Vishakhapatnam (VSKP)",
  "Cuttack (CTC)",
  "Raipur Junction (R)",
  "Chandigarh (CDG)",
  "Ludhiana Junction (LDH)",
  "Coimbatore Junction (CBE)",
  "Agra Cantt (AGC)",
  "Allahabad Junction (ALD)",
  "Indore Junction (INDB)",
  "Jammu Tawi (JAT)",
  "Jodhpur Junction (JU)",
  "Kota Junction (KOTA)",
  "Ranchi (RNC)",
  "Vadodara Junction (BRC)",
  "Tiruchchirapali (TPJ)",
  "Durgapur (DGR)",
  "Erode Junction (ED)",
  "Rourkela (ROU)",
  "Shoranur Junction (SRR)",
  "Guntur Junction (GNT)",
  "Gorakhpur Junction (GKP)",
  "Jhansi Junction (JHS)",
  "Dhanbad Junction (DHN)",
  "Katihar Junction (KIR)",
  "Mangalore Central (MAQ)",
  "Tatanagar Junction (TATA)",
  "Siliguri Junction (SGUJ)",
  "Bikaner Junction (BKN)",
  "Bhusaval Junction (BSL)",
  "Udaipur City (UDZ)",
  "Ajmer Junction (AII)",
  "Aurangabad (AWB)",
  "Solapur (SUR)",
  "Gaya Junction (GAYA)",
  "Jabalpur (JBP)",
  "Mysore Junction (MYS)",
  "Puri (PURI)",
  "Sambalpur (SBP)",
  "Haridwar Junction (HW)",
  "Dehradun (DDN)",
  "Kozhikode (CLT)",
  "Nashik Road (NK)",
  "Vijayawada (BZA)",
  "Bareilly (BE)",
  "Moradabad (MB)",
  "Hajipur Junction (HJP)",
  "Muzaffarpur Junction (MFP)",
  "Madhubani (MBI)",
  "Darbhanga Junction (DBG)",
  "Begusarai (BGS)",
  "Samastipur Junction (SPJ)",
  "Saharsa Junction (SHC)",
  "Rajendra Nagar (RJPB)",
  "New Jalpaiguri (NJP)",
  "Katpadi Junction (KPD)",
  "Palakkad Junction (PGT)",
  "Gulbarga (GR)",
  "Belagavi (BGM)",
  "Hubballi Junction (UBL)",
  "Hosapete Junction (HPT)",
  "Ballari Junction (BAY)",
  "Dharwad (DWR)",
  "Kalaburagi Junction (KLBG)",
  "Chitradurga (CTA)",
  "Hassan Junction (HAS)",
  "Tumkur (TK)",
  "Bidar (BIDR)",
  "Raichur (RC)",
  "Anantapur (ATP)",
  "Kurnool City (KRNT)",
  "Cuddapah (HX)",
  "Ongole (OGL)",
  "Tenali Junction (TEL)",
  "Eluru (EE)",
  "Rajahmundry (RJY)",
  "Srikakulam Road (CHE)",
  "Vizianagaram Junction (VZM)",
  "Kakinada Town (CCT)",
  "Nellore (NLR)",
  "Guntur (GNT)",
  "Machilipatnam (MTM)",
  "Nalgonda (NLDA)",
  "Warangal (WL)",
  "Karimnagar (KRMR)",
  "Khammam (KMT)",
  "Mahbubnagar (MBNR)",
  "Nizamabad (NZB)",
  "Zahirabad (ZB)",
  "Tandur (TDU)",
  "Bhadrachalam Road (BDCR)",
  "Nagarkurnool (NL)",
  "Medak (MZ)",
  "Nirmal (NR)",
  "Kamareddi (KMC)",
  "Yadgir (YG)",
  "Gadag Junction (GDG)",
  "Bijapur (BJP)",
  "Bagalkot (BGK)",
  "Davanagere (DVG)",
  "Chikjajur Junction (JRU)",
  "Birur Junction (RRB)",
  "Shivamogga Town (SMET)",
  "Haveri (HVR)",
  "Kottayam (KTYM)",
  "Kollam Junction (QLN)",
  "Thrissur (TCR)",
  "Thalassery (TLY)",
  "Kannur (CAN)",
  "Kasargod (KGQ)",
  "Alappuzha (ALLP)",
  "Kayamkulam Junction (KYJ)",
  "Ernakulam Town (ERN)",
  "Ernakulam Junction (ERS)",
  "Punalur (PUU)",
  "Varkala (VAK)",
  "Kanhangad (KZE)",
  "Payyanur (PAY)",
  "Nileshwar (NLE)",
  "Kasaragod (KGQ)",
  "Guwahati (GHY)",
  "Lumding Junction (LMG)",
  "Silchar (SCL)",
  "Dibrugarh Town (DBRT)",
  "Tinsukia Junction (TSK)",
  "Mariani Junction (MXN)",
  "Rangiya Junction (RNY)",
  "New Tinsukia Junction (NTSK)",
  "Kamakhya Junction (KYQ)",
  "Dimapur (DMV)",
  "Diphu (DPU)",
  "Hojai (HJI)",
  "Simaluguri Junction (SLGR)",
  "Bongaigaon (BNGN)",
  "Barpeta Road (BPRD)",
  "Nalbari (NLV)",
  "Goalpara Town (GLPT)",
  "Kokrajhar (KOJ)",
  "New Bongaigaon (NBQ)",
  "Dhemaji (DMC)",
  "North Lakhimpur (NLP)",
  "Jorhat Town (JTTN)",
  "Furkating Junction (FKG)",
  "Tezpur (TZTB)",
  "Barak Valley (BVL)",
  "Silapathar (SPTR)",
  "Katihar Junction (KIR)",
  "Purnia Junction (PRNA)",
  "Araria Court (ARQ)",
  "Saharsa Junction (SHC)",
  "Agra Fort (AF)",
  "Amritsar Junction (ASR)",
  "Haridwar Junction (HW)",
  "Dehradun (DDN)",
  "Rishikesh (RKSH)",
  "Ujjain Junction (UJN)",
  "Jaisalmer (JSM)",
  "Jodhpur Junction (JU)",
  "Kanyakumari (CAPE)",
  "Tirupati (TPTY)",
  "Madgaon (MAO)",
  "Ernakulam Junction (ERS)",
  "Varanasi Junction (BSB)",
  "Lucknow NR (LKO)",
  "Gaya Junction (GAYA)",
  "Guwahati (GHY)",
  "Kochi (ERS)",
  "Kozhikode (CLT)",
  "Thiruvananthapuram Central (TVC)",
  "Mysore Junction (MYS)",
  "Chandigarh (CDG)",
  "Shimla (SML)",
  "Kalka (KLK)",
  "Siliguri Junction (SGUJ)",
  "New Jalpaiguri (NJP)",
  "Darjeeling (DJ)",
  "Jaipur Junction (JP)",
  "Udaipur City (UDZ)",
  "Ajmer Junction (AII)",
  "Pushkar Terminus (PUHT)",
  "Mount Abu (ABR)",
  "Rameswaram (RMM)",
  "Madurai Junction (MDU)",
  "Mahabalipuram (MCP)",
  "Hampi (HPT)",
  "Goa (VSG)",
  "Pondicherry (PDY)",
  "Andaman & Nicobar (PORT BLAIR)",
  "Chennai Central (MAS)",
  "Chennai Egmore (MS)",
  "Coimbatore Junction (CBE)",
  "Madurai Junction (MDU)",
  "Tiruchchirappalli Junction (TPJ)",
  "Salem Junction (SA)",
  "Erode Junction (ED)",
  "Tiruppur (TUP)",
  "Dindigul Junction (DG)",
  "Tirunelveli Junction (TEN)",
  "Tuticorin (TN)",
  "Nagercoil Junction (NCJ)",
  "Rameswaram (RMM)",
  "Kanyakumari (CAPE)",
  "Kodaikanal Road (KQN)",
  "Ooty (UAM)",
  "Mettupalayam (MTP)",
  "Coonoor (ONR)",
  "Kanchipuram (CJ)",
  "Karaikudi Junction (KKDI)",
  "Virudhunagar Junction (VPT)",
  "Sivakasi (SVKS)",
  "Srivilliputtur (SVPR)",
  "Tiruchendur (TCN)",
  "Nagapattinam (NGT)",
  "Thanjavur Junction (TJ)",
  "Kumbakonam (KMU)",
  "Mayiladuthurai Junction (MV)",
  "Chidambaram (CDM)",
  "Villupuram Junction (VM)",
  "Vellore Cantonment (VLR)",
  "Vellore Town (VT)",
  "Katpadi Junction (KPD)",
  "Arakkonam Junction (AJJ)",
  "Jolarpettai Junction (JTJ)",
  "Ambur (AB)",
  "Vaniyambadi (VN)",
  "Krishnarajapuram (KJM)",
  "Dharmapuri (DPJ)",
  "Hosur (HSRA)",
  "Salem Town (SXT)",
  "Tirupattur (TPT)",
  "Tambaram (TBM)",
  "Chengalpattu Junction (CGL)",
  "Arakkonam Junction (AJJ)",
  "Gummidipundi (GPD)",
  "Tindivanam (TMV)",
  "Chidambaram (CDM)",
  "Cuddalore Port Junction (CUPJ)",
  "Vriddhachalam Junction (VRI)",
  "Perambalur (PEI)",
  "Ariyalur (ALU)",
  "Manapparai (MPA)",
  "Kulithalai (KLT)",
  "Karur Junction (KRR)",
  "Pugalur (PGR)",
  "Namakkal (NMKL)",
  "Attur (ATU)",
  "Rasipuram (RASP)",
  "Sankarankovil (SNKL)",
  "Rajapalayam (RJPM)",
  "Srivilliputtur (SVPR)",
  "Virudhunagar Junction (VPT)",
  "Kovilpatti (CVP)",
  "Sivaganga (SVGA)",
  "Manamadurai Junction (MNMD)",
  "Paramakudi (PMK)",
  "Ramanathapuram (RMD)",
  "Tiruchendur (TCN)",
  "Karaikkudi Junction (KKDI)",
  "Pudukkottai (PDKT)",
  "Sivaganga (SVGA)",
  "Manaparai (MPA)",
  "Papanasam (PML)",
  "Kumbakonam (KMU)",
  "Thiruvarur Junction (TVR)",
  "Nagapattinam (NGT)",
  "Velankanni (VLNK)",
  "Mannargudi (MQ)",
  "Perambur (PER)",
  "Mambalam (MBM)",
  "Guindy (GDY)",
  "St. Thomas Mount (STM)",
  "Pallavaram (PV)",
  "Chromepet (CMP)",
  "Tirusulam (TLM)",
  "Tambaram (TBM)",
  "Perungalathur (PRGL)",
  "Vandalur (VDR)",
  "Guduvancheri (GI)",
  "Urapakkam (UPM)",
  "Chengalpattu Junction (CGL)",
  "Kanchipuram (CJ)",
  "Walajabad (WJ)",
  "Arakkonam Junction (AJJ)",
  "Vijayawada Junction (BZA)",
  "Visakhapatnam (VSKP)",
  "Tirupati (TPTY)",
  "Guntur Junction (GNT)",
  "Rajahmundry (RJY)",
  "Nellore (NLR)",
  "Kakinada Town (CCT)",
  "Srikakulam Road (CHE)",
  "Anakapalle (AKP)",
  "Kadapa (HX)",
  "Anantapur (ATP)",
  "Eluru (EE)",
  "Ongole (OGL)",
  "Tenali Junction (TEL)",
  "Chittoor (CTO)",
  "Dharmavaram Junction (DMM)",
  "Tadepalligudem (TDD)",
  "Renigunta Junction (RU)",
  "Puttaparthi (PRTI)",
  "Machilipatnam (MTM)",
  "Proddatur (PRDT)",
  "Naharlagun (NHLN)",
  "Bhalukpong (BXP)",
  "Harmuti (HMY)",
  "North Lakhimpur (NLP)",
  "Dibrugarh Town (DBRT)",
  "Tinsukia Junction (TSK)",
  "Guwahati (GHY)",
  "Silchar (SCL)",
  "Guwahati (GHY)",
  "Dibrugarh (DBRG)",
  "Tinsukia (TSK)",
  "Silchar (SCL)",
  "Jorhat Town (JTTN)",
  "Lumding Junction (LMG)",
  "New Bongaigaon (NBQ)",
  "Rangiya Junction (RNY)",
  "Diphu (DPU)",
  "Tezpur (TZTB)",
  "Hojai (HJI)",
  "Bongaigaon (BNGN)",
  "Kokrajhar (KOJ)",
  "Goalpara Town (GLPT)",
  "Barpeta Road (BPRD)",
  "Mariani Junction (MXN)",
  "Simaluguri Junction (SLGR)",
  "Dhemaji (DMC)",
  "North Lakhimpur (NLP)",
  "Silapathar (SPTR)",
  "Patna Junction (PNBE)",
  "Gaya Junction (GAYA)",
  "Muzaffarpur Junction (MFP)",
  "Bhagalpur (BGP)",
  "Darbhanga Junction (DBG)",
  "Purnia Junction (PRNA)",
  "Barauni Junction (BJU)",
  "Katihar Junction (KIR)",
  "Hajipur Junction (HJP)",
  "Samastipur Junction (SPJ)",
  "Siwan Junction (SV)",
  "Chhapra Junction (CPR)",
  "Saharsa Junction (SHC)",
  "Ara Junction (ARA)",
  "Begusarai (BGS)",
  "Buxar (BXR)",
  "Munger (MGR)",
  "Nawada (NWD)",
  "Sitamarhi (SMI)",
  "Jamalpur Junction (JMP)",
  "Raipur Junction (R)",
  "Bilaspur Junction (BSP)",
  "Durg Junction (DURG)",
  "Bhilai Power House (BPHB)",
  "Korba (KRBA)",
  "Raigarh (RIG)",
  "Jagdalpur (JDB)",
  "Raj Nandgaon (RJN)",
  "Dalli Rajhara (DRZ)",
  "Ambikapur (ABKP)",
  "Champa Junction (CPH)",
  "Dongargarh (DGG)",
  "Kanker Road (KRRD)",
  "Mahasamund (MSMD)",
  "Tilda (TLD)",
  "Uslapur (USL)",
  "Janjgir Naila (NIA)",
  "Ahiwara (AWR)",
  "Baikunthpur Road (BRH)",
  "Dharamjaigarh (DHRJ)",
  "Madgaon (MAO)",
  "Vasco da Gama (VSG)",
  "Thivim (THVM)",
  "Karmali (KRMI)",
  "Canacona (CNO)",
  "Sanvordem Curchorem (SVM)",
  "Pernem (PERN)",
  "Balli (BLLI)",
  "Verna (VEN)",
  "Margao (MRGO)",
  "Tiracol (TCO)",
  "Collem (COL)",
  "Dudhsagar Waterfalls (DSGR)",
  "Ahmedabad Junction (ADI)",
  "Surat (ST)",
  "Vadodara Junction (BRC)",
  "Rajkot Junction (RJT)",
  "Bhavnagar Terminus (BVC)",
  "Jamnagar (JAM)",
  "Gandhidham Junction (GIMB)",
  "Palanpur Junction (PNU)",
  "Dwarka (DWK)",
  "Somnath (SMNH)",
  "Porbandar (PBR)",
  "Nadiad Junction (ND)",
  "Anand Junction (ANND)",
  "Junagadh Junction (JND)",
  "Bhuj (BHUJ)",
  "Valsad (BL)",
  "Navsari (NVS)",
  "Godhra Junction (GDA)",
  "Mehsana Junction (MSH)",
  "Vapi (VAPI)",
  "Ambala Cantt Junction (UMB)",
  "Kurukshetra Junction (KKDE)",
  "Rohtak Junction (ROK)",
  "Hisar Junction (HSR)",
  "Panipat Junction (PNP)",
  "Bhiwani Junction (BNW)",
  "Rewari Junction (RE)",
  "Karnal (KUN)",
  "Jind Junction (JIND)",
  "Bahadurgarh (BGZ)",
  "Sonipat (SNP)",
  "Gurgaon (GGN)",
  "Faridabad (FDB)",
  "Palwal (PWL)",
  "Sirsa (SSA)",
  "Kaithal (KLE)",
  "Yamunanagar Jagadhri (YJUD)",
  "Hansi (HNS)",
  "Narnaul (NNL)",
  "Mahendragarh (MHRG)",
  "Shimla (SML)",
  "Kalka (KLK)",
  "Solan (SOL)",
  "Una Himachal (UHL)",
  "Joginder Nagar (JDNX)",
  "Pathankot (PTK)",
  "Palampur Himachal (PLMX)",
  "Kangra Mandir (KGMR)",
  "Kullu (KUU)",
  "Mandi (MND)",
  "Dharamshala (DHRMS)",
  "Chamba (CHMB)",
  "Dalhousie (DLHS)",
  "Hamirpur (HMP)",
  "Bilaspur (BLSP)",
  "Nahan (NHN)",
  "Sundernagar (SDNR)",
  "Rampur Bushahr (RMB)",
  "Kinnaur (KNUR)",
  "Spiti (SPTI)",
  "Jammu Tawi (JAT)",
  "Udhampur (UHP)",
  "Katra (KATRA)",
  "Srinagar (SINA)",
  "Anantnag (ANT)",
  "Baramulla (BRML)",
  "Banihal (BAHL)",
  "Qazigund (QG)",
  "Pulwama (PLMA)",
  "Kupwara (KPRA)",
  "Poonch (PNCH)",
  "Rajouri (RJI)",
  "Doda (DDA)",
  "Kishtwar (KTW)",
  "Reasi (RSI)",
  "Kathua (KTHU)",
  "Budgam (BDGM)",
  "Handwara (HDW)",
  "Sopore (SPE)",
  "Ganderbal (GDBL)",
  "Ranchi Junction (RNC)",
  "Dhanbad Junction (DHN)",
  "Jamshedpur (TATA)",
  "Bokaro Steel City (BKSC)",
  "Hazaribagh (HZD)",
  "Deoghar (DGHR)",
  "Dumka (DUMK)",
  "Giridih (GRD)",
  "Palamu (PLM)",
  "Daltonganj (DTO)",
  "Ghatshila (GTS)",
  "Ramgarh (RMG)",
  "Jharia (JHIA)",
  "Chaibasa (CBSA)",
  "Godda (GODA)",
  "Pakur (PKR)",
  "Khunti (KHNT)",
  "Simdega (SIMD)",
  "Seraikela (SKLA)",
  "Latehar (LTHR)",
  "Bengaluru City Junction (SBC)",
  "Hubli Junction (UBL)",
  "Mysuru Junction (MYS)",
  "Mangalore Junction (MAJN)",
  "Belagavi (BGM)",
  "Dharwad (DWR)",
  "Ballari Junction (BAY)",
  "Kalaburagi (KLBG)",
  "Hospet Junction (HPT)",
  "Bijapur (BJP)",
  "Bagalkot (BGK)",
  "Bidar (BIDR)",
  "Shimoga Town (SMET)",
  "Hassan Junction (HAS)",
  "Chikmagalur (CMGR)",
  "Tumakuru (TK)",
  "Mandya (MYA)",
  "Udupi (UD)",
  "Raichur (RC)",
  "Davangere (DVG)",
  "Thiruvananthapuram Central (TVC)",
  "Kochi Ernakulam Junction (ERS)",
  "Kozhikode (CLT)",
  "Kollam Junction (QLN)",
  "Thrissur (TCR)",
  "Alappuzha (ALLP)",
  "Kottayam (KTYM)",
  "Palakkad Junction (PGT)",
  "Kannur (CAN)",
  "Kasaragod (KGQ)",
  "Tirur (TIR)",
  "Shoranur Junction (SRR)",
  "Mavelikara (MVLK)",
  "Kayamkulam Junction (KYJ)",
  "Varkala Sivagiri (VAK)",
  "Chengannur (CNGR)",
  "Ottapalam (OTP)",
  "Guruvayur (GUV)",
  "Nilambur Road (NIL)",
  "Angamaly (AFK)",
  "Bhopal Junction (BPL)",
  "Indore Junction (INDB)",
  "Jabalpur Junction (JBP)",
  "Gwalior (GWL)",
  "Ujjain Junction (UJN)",
  "Katni Junction (KTE)",
  "Rewa (REWA)",
  "Itarsi Junction (ET)",
  "Ratlam Junction (RTM)",
  "Satna (STA)",
  "Chhindwara Junction (CWA)",
  "Hoshangabad (HBD)",
  "Sagar (SGO)",
  "Dewas (DWX)",
  "Khajuraho (KURJ)",
  "Guna (GUNA)",
  "Shivpuri (SVPI)",
  "Betul (BZU)",
  "Shahdol (SDL)",
  "Vidisha (BHS)",
  "Mumbai Central (BCT)",
  "Chhatrapati Shivaji Maharaj Terminus (CSMT)",
  "Pune Junction (PUNE)",
  "Nagpur Junction (NGP)",
  "Thane (TNA)",
  "Nashik Road (NK)",
  "Aurangabad (AWB)",
  "Shirdi (SNSI)",
  "Kolhapur (KOP)",
  "Solapur (SUR)",
  "Ahmednagar (ANG)",
  "Lonavala (LNL)",
  "Satara (STR)",
  "Ratnagiri (RN)",
  "Kalyan Junction (KYN)",
  "Dadar Central (DR)",
  "Bhusawal Junction (BSL)",
  "Amravati (AMI)",
  "Akola Junction (AK)",
  "Jalgaon Junction (JL)",
  "Jiribam (JRBM)",
  "Imphal (IMF)",
  "Senapati (SNP)",
  "Ukhrul (UKR)",
  "Thoubal (THBL)",
  "Churachandpur (CRCP)",
  "Bishnupur (BSPR)",
  "Chandel (CDL)",
  "Kangpokpi (KPI)",
  "Tamenglong (TMLG)",
  "Shillong (SHLG)",
  "Cherrapunji (CHPJ)",
  "Tura (TRA)",
  "Nongpoh (NGP)",
  "Mairang (MRNG)",
  "Jowai (JWAI)",
  "Baghmara (BGM)",
  "Williamnagar (WMG)",
  "Resubelpara (RSBP)",
  "Nongstoin (NGST)",
  "Bairabi (BRB)",
  "Kolasib (KLB)",
  "Aizawl (AZL)",
  "Serchhip (SCP)",
  "Champhai (CHP)",
  "Lunglei (LGL)",
  "Saiha (SIA)",
  "Lawngtlai (LWT)",
  "Mamit (MMT)",
  "Reiek (REIK)",
  "Dimapur (DMV)",
  "Kohima (KHM)",
  "Mokokchung (MKG)",
  "Wokha (WKA)",
  "Tuensang (TSA)",
  "Mon (MON)",
  "Phek (PHEK)",
  "Zunheboto (ZBTO)",
  "Kiphire (KPIR)",
  "Longleng (LLNG)",
  "Bhubaneswar (BBS)",
  "Cuttack (CTC)",
  "Puri (PURI)",
  "Rourkela (ROU)",
  "Sambalpur (SBP)",
  "Berhampur (BAM)",
  "Balasore (BLS)",
  "Angul (ANGL)",
  "Jharsuguda Junction (JSG)",
  "Koraput (KRPU)",
  "Rayagada (RGDA)",
  "Jeypore (JYP)",
  "Khurda Road Junction (KUR)",
  "Bargarh Road (BRGA)",
  "Balangir (BLGR)",
  "Kendujhargarh (KDJR)",
  "Baripada (BPO)",
  "Bhadrak (BHC)",
  "Jagatsinghpur (JSPT)",
  "Nabarangpur (NBRP)",
  "Amritsar Junction (ASR)",
  "Ludhiana Junction (LDH)",
  "Jalandhar City Junction (JUC)",
  "Patiala (PTA)",
  "Bathinda Junction (BTI)",
  "Firozpur Cantt (FZR)",
  "Hoshiarpur (HSX)",
  "Kapurthala (KXH)",
  "Pathankot (PTK)",
  "Gurdaspur (GSP)",
  "Barnala (BNN)",
  "Faridkot (FDK)",
  "Moga (MOGA)",
  "Sangrur (SAG)",
  "Abohar (ABS)",
  "Fatehgarh Sahib (FGSB)",
  "Rupnagar (RPAR)",
  "Nawanshahr Doaba (NRO)",
  "Muktsar (MKS)",
  "Mansa (MSZ)",
  "Jaipur Junction (JP)",
  "Jodhpur Junction (JU)",
  "Udaipur City (UDZ)",
  "Ajmer Junction (AII)",
  "Bikaner Junction (BKN)",
  "Kota Junction (KOTA)",
  "Alwar Junction (AWR)",
  "Bharatpur Junction (BTE)",
  "Jaisalmer (JSM)",
  "Chittaurgarh Junction (COR)",
  "Sawai Madhopur Junction (SWM)",
  "Bhilwara (BHL)",
  "Barmer (BME)",
  "Nagaur (NGO)",
  "Sikar Junction (SIKR)",
  "Dungarpur (DNRP)",
  "Tonk (TONK)",
  "Jhalawar City (JHW)",
  "Karauli (KRLI)",
  "Rajsamand (RJD)",
  "Gangtok (GNGT)",
  "Rangpo (RPO)",
  "Pakyong (PYG)",
  "Mangan (MNGN)",
  "Gyalshing (GYS)",
  "Ravangla (RVL)",
  "Namchi (NMCI)",
  "Soreng (SRNG)",
  "Singtam (SGTM)",
  "Chungthang (CNGT)",
  "Chennai Central (MAS)",
  "Coimbatore Junction (CBE)",
  "Madurai Junction (MDU)",
  "Tiruchirappalli Junction (TPJ)",
  "Salem Junction (SA)",
  "Tirunelveli Junction (TEN)",
  "Erode Junction (ED)",
  "Vellore Katpadi Junction (KPD)",
  "Tanjore Junction (TJ)",
  "Nagercoil Junction (NCJ)",
  "Rameswaram (RMM)",
  "Kanyakumari (CAPE)",
  "Ooty (UAM)",
  "Kodaikanal Road (KQN)",
  "Coonoor (ONR)",
  "Yercaud (YRD)",
  "Velankanni (VLNK)",
  "Kumbakonam (KMU)",
  "Mahabalipuram (MBPM)",
  "Chidambaram (CDM)",
  "Hyderabad Deccan (HYB)",
  "Secunderabad Junction (SC)",
  "Warangal (WL)",
  "Kazipet Junction (KZJ)",
  "Khamam (KMT)",
  "Mahbubnagar (MBNR)",
  "Nizamabad (NZB)",
  "Karimnagar (KRMR)",
  "Medchal (MED)",
  "Nalgonda (NLDA)",
  "Ramagundam (RDM)",
  "Vikarabad Junction (VKB)",
  "Zahirabad (ZB)",
  "Bhadrachalam Road (BDCR)",
  "Dornakal Junction (DKJ)",
  "Peddapalli (PDPL)",
  "Manchiryal (MCI)",
  "Adilabad (ADB)",
  "Siddipet (SDPT)",
  "Suryapet (SUIT)",
  "Agartala (AGTL)",
  "Dharmanagar (DMR)",
  "Udaipur Tripura (UDPU)",
  "Kailashahar (KLSR)",
  "Teliamura (TLMR)",
  "Belonia (BENA)",
  "Sabroom (SBRM)",
  "Ambassa (ABSA)",
  "Kumarghat (KUGT)",
  "Khowai (KHW)",
  "Lucknow Junction (LJN)",
  "Kanpur Central (CNB)",
  "Varanasi Junction (BSB)",
  "Agra Cantt (AGC)",
  "Allahabad Junction (ALD)",
  "Gorakhpur Junction (GKP)",
  "Bareilly Junction (BE)",
  "Mathura Junction (MTJ)",
  "Ghaziabad (GZB)",
  "Meerut City (MTC)",
  "Moradabad Junction (MB)",
  "Jhansi Junction (JHS)",
  "Aligarh Junction (ALJN)",
  "Faizabad Junction (FD)",
  "Saharanpur Junction (SRE)",
  "Etawah Junction (ETW)",
  "Sultanpur Junction (SLN)",
  "Deoria Sadar (DEOS)",
  "Ballia (BUI)",
  "Firozabad (FZD)",
  "Dehradun (DDN)",
  "Haridwar Junction (HW)",
  "Rishikesh (RKSH)",
  "Kathgodam (KGM)",
  "Nainital (NNTL)",
  "Almora (ALMR)",
  "Haldwani (HDW)",
  "Rudrapur City (RUPC)",
  "Laksar Junction (LRJ)",
  "Roorkee (RK)",
  "Kotdwar (KTW)",
  "Pauri (PAUI)",
  "Bageshwar (BGSR)",
  "Champawat (CPWT)",
  "Pithoragarh (PITH)",
  "Chamba (CHMB)",
  "Tehri (THRI)",
  "New Tehri (NTRI)",
  "Devprayag (DPRG)",
  "Ranikhet (RNKT)",
  "Howrah Junction (HWH)",
  "Sealdah (SDAH)",
  "Kolkata Chitpur (KOAA)",
  "Siliguri Junction (SGUJ)",
  "Darjeeling (DJ)",
  "New Jalpaiguri (NJP)",
  "Durgapur (DGR)",
  "Asansol Junction (ASN)",
  "Malda Town (MLDT)",
  "Kharagpur Junction (KGP)",
  "Haldia (HLZ)",
  "Bardhaman Junction (BWN)",
  "Alipurduar Junction (APDJ)",
  "Cooch Behar (COB)",
  "Bankura (BQA)",
  "Purulia (PRR)",
  "Rampurhat (RPH)",
  "Bolepur Shantiniketan (BHP)",
  "Krishnanagar City Junction (KNJ)",
  "Barrackpore (BP)",
];

const trainsNames = [
  "Rajdhani Express",
  "Shatabdi Express",
  "Duronto Express",
  "Garib Rath Express",
  "Jan Shatabdi Express",
  "Vande Bharat Express",
  "Humsafar Express",
  "Tejas Express",
  "Antyodaya Express",
  "Sampark Kranti Express",
  "Mahamana Express",
  "Deccan Queen",
  "Karnataka Express",
  "Chennai Express",
  "Punjab Mail",
  "Gujarat Mail",
  "Howrah Mail",
  "Grand Trunk Express",
  "Dakshin Express",
  "Tamil Nadu Express",
  "Goa Express",
  "Kerala Express",
  "Matsyagandha Express",
  "Mandovi Express",
  "Netravati Express",
  "Konkan Kanya Express",
  "Bangalore Mail",
  "Nizamuddin Express",
  "Kalka Mail",
  "Jhelum Express",
  "Taj Express",
  "Chhattisgarh Express",
  "Chennai Mail",
  "Patna Express",
  "Lucknow Mail",
  "Pratap Express",
  "Himgiri Express",
  "Kashmir Valley Express",
  "Uttar Sampark Kranti Express",
  "Swarna Jayanti Express",
  "Dibrugarh Express",
  "Kamakhya Express",
  "Agartala Express",
  "Guwahati Express",
  "Ganga Sagar Express",
  "Vivek Express",
  "Sikkim Mahananda Express",
  "Coromandel Express",
  "Ganga Kaveri Express",
  "Andaman Express",
  "Doon Express",
  "Mussoorie Express",
  "Kumbh Express",
  "Kalka Shatabdi Express",
  "Dehradun Shatabdi Express",
  "Ajmer Shatabdi Express",
  "Amritsar Shatabdi Express",
  "Kanpur Shatabdi Express",
  "Lucknow Shatabdi Express",
  "Bhopal Shatabdi Express",
  "Bilaspur Rajdhani Express",
  "Secunderabad Rajdhani Express",
  "Bhubaneswar Rajdhani Express",
  "Trivandrum Rajdhani Express",
  "Jammu Tawi Rajdhani Express",
  "Dibrugarh Rajdhani Express",
  "Agartala Rajdhani Express",
  "Howrah Rajdhani Express",
  "Sealdah Rajdhani Express",
  "Ranchi Rajdhani Express",
  "Patna Rajdhani Express",
  "Mumbai Rajdhani Express",
  "Chennai Rajdhani Express",
  "Bangalore Rajdhani Express",
  "Kochuveli Garib Rath Express",
  "Nizamuddin Garib Rath Express",
  "Yuva Express",
  "Andhra Pradesh Express",
  "Bihar Sampark Kranti Express",
  "Rajasthan Sampark Kranti Express",
  "Goa Sampark Kranti Express",
  "Karnataka Sampark Kranti Express",
  "Kerala Sampark Kranti Express",
  "Odisha Sampark Kranti Express",
  "Haryana Sampark Kranti Express",
  "Chandigarh Shatabdi Express",
  "Mysore Shatabdi Express",
  "Guwahati Shatabdi Express",
  "Indore Shatabdi Express",
  "Lucknow Tejas Express",
  "Mumbai Central Tejas Express",
  "Chennai Tejas Express",
  "Madgaon Tejas Express",
  "Vijayawada Tejas Express",
  "Patna Tejas Express",
  "Varanasi Tejas Express",
  "Agra Tejas Express",
  "Amritsar Golden Temple Mail",
  "Mumbai LTT - Secunderabad Duronto Express",
  "Howrah - Mumbai CST Duronto Express",
  "Sealdah - Puri Duronto Express",
  "Chennai - Coimbatore Shatabdi Express",
  "Delhi - Dehradun Shatabdi Express",
  "Jammu Tawi Express",
  "Himgiri Express",
  "Darjeeling Mail",
  "Amarnath Express",
  "Konkan Kanya Express",
  "Deccan Odyssey",
  "Palace on Wheels",
  "Maharaja Express",
  "Golden Chariot",
  "Royal Rajasthan on Wheels",
  "Bharat Darshan Express",
  "Tourist Train to Goa",
  "Maharashtra Express",
  "Haryana Express",
  "Kutch Express",
  "Malwa Express",
  "Ajanta Express",
  "Janshatabdi Express",
  "Malabar Express",
  "Mangala Lakshadweep Express",
  "Nizamuddin Duronto Express",
  "Rajasthan Duronto Express",
  "Swaraj Express",
  "Mysore Express",
  "Shalimar Express",
  "Yesvantpur Express",
  "Marathwada Express",
  "Vidarbha Express",
  "Marusagar Express",
  "Mandore Express",
  "Gandhidham Express",
  "Bhuj Express",
  "Jamnagar Express",
  "Somnath Express",
  "Kaveri Express",
  "Vaigai Express",
  "Pandian Express",
  "Rockfort Express",
  "Mangalore Express",
  "Ernakulam Express",
  "Madurai Express",
  "Cheran Express",
  "Trichy Express",
  "Palani Express",
  "Anantapuri Express",
  "Pothigai Express",
  "Chendur Express",
  "Nilgiri Express",
  "Kodaikanal Express",
  "Palakkad Express",
  "Thirukural Express",
  "Jodhpur Express",
  "Barmer Express",
  "Bikaner Express",
  "Udaipur Express",
  "Bhilwara Express",
  "Nagaur Express",
  "Pushkar Express",
  "Jaisalmer Express",
  "Sujangarh Express",
  "Bhagat Ki Kothi Express",
  "Ramdevra Express",
  "Pokaran Express",
  "Khajuraho Express",
  "Bundelkhand Express",
  "Vindhyachal Express",
  "Mahakaushal Express",
  "Bhopal Express",
  "Jabalpur Express",
  "Satpura Express",
  "Amarkantak Express",
  "Dadar Express",
  "Patna Express",
  "Danapur Express",
  "Vikramshila Express",
  "Rajendra Nagar Express",
  "Mithila Express",
  "Shramjeevi Express",
  "Magadh Express",
  "Ganga Damodar Express",
  "Budh Purnima Express",
  "Satyagraha Express",
  "Shaheed Express",
  "North East Express",
  "Bihar Sampark Kranti Express",
  "Lichchavi Express",
  "Vaishali Express",
  "Gorakhdham Express",
  "Rapti Sagar Express",
  "Sarnath Express",
  "Chhapra Express",
  "Siwan Express",
  "Ghazipur Express",
  "Varanasi Express",
  "Mughalsarai Express",
  "Prayagraj Express",
  "Sangam Express",
  "Kanpur Express",
  "Lucknow Express",
  "Rohtak Express",
  "Ambala Express",
  "Panipat Express",
  "Rewari Express",
  "Hisar Express",
  "Bhiwani Express",
  "Fatehabad Express",
  "Sirsa Express",
  "Sonipat Express",
  "Rohtak Express",
  "Jind Express",
  "Kaithal Express",
  "Karnal Express",
  "Kurukshetra Express",
  "Yamunanagar Express",
  "Shimla Express",
  "Chandigarh Express",
  "Chhattisgarh Sampark Kranti Express",
  "Bilaspur Express",
  "Durg Express",
  "Raipur Express",
  "Bhilai Express",
  "Korba Express",
  "Surat Express",
  "Nagpur Express",
  "Puri Express",
  "Rourkela Express",
  "Jharsuguda Express",
  "Sambalpur Express",
  "Bolangir Express",
  "Titlagarh Express",
  "Rayagada Express",
  "Vishakhapatnam Express",
  "Koraput Express",
  "Paradeep Express",
  "Bhadrak Express",
  "Kendujhargarh Express",
  "Angul Express",
  "Khurda Express",
  "Balasore Express",
  "Baripada Express",
  "Cuttack Express",
  "Rairangpur Express",
  "Ranchi Express",
  "Jamshedpur Express",
  "Tatanagar Express",
  "Dhanbad Express",
  "Bokaro Express",
  "Hazaribagh Express",
  "Ramgarh Express",
  "Giridih Express",
  "Palamu Express",
  "Latehar Express",
  "Garhwa Express",
  "Chaibasa Express",
  "Simdega Express",
  "Lohardaga Express",
  "Deoghar Express",
  "Dumka Express",
  "Godda Express",
  "Pakur Express",
  "Sahebganj Express",
  "Bihar Express",
  "Madhubani Express",
  "Darbhanga Express",
  "Jayanagar Express",
  "Bettiah Express",
  "Gopalganj Express",
  "Siwan Express",
  "Sonepur Express",
  "Samastipur Express",
  "Begusarai Express",
  "Khagaria Express",
  "Katihar Express",
  "Purnia Express",
  "Saharsa Express",
  "Madhepura Express",
  "Araria Express",
  "Kishanganj Express",
  "Munger Express",
  "Bhagalpur Express",
  "Banka Express",
  "Navgachia Express",
  "Khagaria Express",
  "Khagaria Express",
];

const generateTrainData = (numEntries) => {
  const trains = [];

  startDate = Date.now();

  endDate = new Date("2024-12-31");

  for (i = 0; i <= numEntries; i++) {
    source =
      railwayStations[Math.floor(Math.random() * railwayStations.length)];

    let destination = [];

    for (railwayStation of railwayStations) {
      if (railwayStation !== source) {
        destination.push(railwayStation);
      }
    }

    destination = destination[Math.floor(Math.random() * destination.length)];

    const departureTime = new Date(
      startDate + Math.floor(Math.random() * (endDate.getTime() - startDate))
    );

    const hours = [1, 2, 3, 4, 5, 7, 8, 12, 9, 10];

    const randomHrs = hours[Math.floor(Math.random() * hours.length)];

    const arrivalTime = new Date(
      departureTime.getTime() + randomHrs * 3600 * 1000
    );

    const trainName =
      trainsNames[Math.floor(Math.random() * trainsNames.length)];

    let trainAbrv = trainName
      .split(" ")
      .map((letter) => letter[0])
      .join("");

    const trainNumber = `${trainAbrv}${Math.floor(Math.random() * 1000)}`;

    const cost = Math.floor(Math.random() * 1000);

    const train = {
      trainNumber: trainNumber,
      trainName: trainName,

      source: source,
      destination: destination,
      departureTime: departureTime,
      arrivalTime: arrivalTime,
      cost: cost,
      currency: "INR",
    };
    trains.push(train);
  }

  return trains;
};

const trainController = {
  addTrain: async (req, res) => {
    try {
      const userId = req.userId;
      const admin = req.userType;

      if (!req.body || Object.keys(req.body).length === 0) {
        return res.status(400).json({ message: "Train data empty" });
      }

      const user = await User.findOne({ _id: userId, userType: admin });

      if (!user) {
        return res.status(400).json({ message: "Unauthorized access" });
      }

      const train = new Train({ ...req.body });

      if (!train) {
        return res.status(400).json({ message: "Train data not added" });
      }

      await train.save();

      res.status(201).json("train data added successfully");
    } catch (err) {
      res.status(500).json({ message: err.message });
    }
  },

  addManyTrains: async (req, res) => {
    try {
      const userId = req.userId;
      const admin = req.userType;

      const user = await User.findOne({ _id: userId, userType: admin });

      if (!user) {
        return res.status(400).json({ message: "Unauthorized" });
      }

      const trainData = generateTrainData(1000);

      const trains = await Train.insertMany(trainData);

      if (!trains) {
        return res.status(400).json({ message: "Train data not added" });
      }

      res.status(201).json("Train data added successfully");
    } catch (err) {
      res.status(500).json({ message: err.message });
    }
  },
};

module.exports = trainController;
